### ISSUE TITLE
API Access?

### ISSUE THREAD

**Issue by jazbek** [TouchBistro/sous-chef#2]
Hey Touchbistro team, I'm working on an app that needs a Dining POS with an api to integrate with. 

Is this awesome-looking API available yet?

**Comment by frankcaron** [comment]
Hi @jazbek, Frank Caron here. I'm the product manager at TouchBistro. Super excited that you managed to find this repo even though we haven't publicized it yet! 

The API is available to select developers for integration, depending on the use case and the app in question. If you want more info, please reach out to me at fcaron@touchbistro.com.
